### ISSUE TITLE
iNalyzer does not package applications that are unencrypted.

### ISSUE THREAD

**Issue by awesomo4000** [appsec-labs/iNalyzer#1]
Accessing:

http://iphone:5544/iNalyzer?App=MyApp-iphone&EOFname=

Returns (from chrome):

Error 324 (net::ERR_EMPTY_RESPONSE): The server closed the connection without sending any data.

packApp.sh fails because iNalyzer5 fails with:

There are no encrypted applications on this device.

**Comment by chilik** [comment]
that is a know bug here is a work around:
1. SSH to device, 
2. cd to /Applications/iNalyzer5.app
3. run ./iNalyzer5 --direct [specifying the full path to your unencrypted application folder with a trailing slash] 
     eg. ./iNalyzer5 --direct /Applications/MobileSafari.app/
4. once packaging is completed check out the /var/root/Documents/iNalzyer/ folder to see your application package
