### ISSUE TITLE
iNalyzer doesn't listen to port 5544 on iPhone 6+ (iOS 8.3)

### ISSUE THREAD

**Issue by ila08** [appsec-labs/iNalyzer#10]

**Comment by ila08** [comment]
Hi Team, 

Just wanted to circle back to check if there is any update on this issue. 

Thanks in advance for the help! 

Best Regards, 
ila Kanti

**Comment by sro-co-il** [comment]
A new version that supports better iOS 8 & 9 was published, Please check it:
https://appsec-labs.com/cydia/
