### ISSUE TITLE
Segmentation fault and port 5544 is not opened on the device. 

### ISSUE THREAD

**Issue by s4n7h0** [appsec-labs/iNalyzer#11]
./iNalyzer is giving following error. When I use the application on the device port 5544 seems not opening. But when I run iNalyzer on the terminal, it seems working, but somehow throws following error too. At the same time, the port is not accessible over network. Also netstat command shows no details for port 5544. 

```
/Applications/iNalyzer5.app/iNalyzer-Deamon.sh: line 58: 13862 Segmentation fault: 11  /usr/bin/cycript -p SpringBoard "/Applications/iNalyzer5.app/${message}"
/Applications/iNalyzer5.app/iNalyzer-Deamon.sh: line 60: 13872 Segmentation fault: 11  /usr/bin/cycript -p SpringBoard "/Applications/iNalyzer5.app/${message}"
/Applications/iNalyzer5.app/iNalyzer-Deamon.sh: line 61: 13878 Segmentation fault: 11  /usr/bin/cycript -p SpringBoard "/Applications/iNalyzer5.app/${message}"
/Applications/iNalyzer5.app/iNalyzer-Deamon.sh: line 62: 13883 Segmentation fault: 11  /usr/bin/cycript -p SpringBoard "/Applications/iNalyzer5.app/${message}"
```

**Comment by tghosth** [comment]
asd

**Comment by st3r30byt3** [comment]
Same problem here. Any ideas?

**Comment by sro-co-il** [comment]
Regarding these problems, we've change the way that iNalyzer works. A new version of iNalyzer was published, available on our cydia repository:
https://appsec-labs.com/cydia/
