### ISSUE TITLE
app run issue

### ISSUE THREAD

**Issue by naveen12** [appsec-labs/iNalyzer#12]
Device= iPod touch
iOS= 9.3.5
Jailbreak = Done
- installed all necessary tools
I have downloaded iNalyzer in device and installed
- through the ssh mode ran the commands like below 
/Applications/iNalyzer.app
./iNalyzer

after this it showing error as "Abort trap: 6"
Please do the needful

**Comment by naveen12** [comment]
ok got it 
after installation reboot is needed

**Comment by nate-red** [comment]
I'm having this issue regardless of reboots.
