### ISSUE TITLE
Binary release...

### ISSUE THREAD

**Issue by essobi** [appsec-labs/iNalyzer#2]
Think the 7.0 release got horked up.
iHacks-iPad:~ root# whoami
root
iHacks-iPad:~ root# dpkg -l | grep -i inalyzer
iHacks-iPad:~ root# apt-cache search inalyzer
com.appsec-labs.inalyzer5 - iNalyzer5 version v7.0b
com.appseclabs.inalyzer - iNalyzer for iOS 4
iHacks-iPad:~ root# apt-get install com.appsec-labs.inalyzer5=7.0b
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  com.appsec-labs.inalyzer5
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 0B/2937kB of archives.
After this operation, 0B of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  com.appsec-labs.inalyzer5
Install these packages without verification [y/N]? y
Selecting previously deselected package com.appsec-labs.inalyzer5.
(Reading database ... 7842 files and directories currently installed.)
Unpacking com.appsec-labs.inalyzer5 (from .../com.appsec-labs.inalyzer5_7.0b_iphoneos-arm.deb) ...
Setting up com.appsec-labs.inalyzer5 (5.5b) ...
iHacks-iPad:~ root# dpkg -l | grep -i inalyzer
ii  com.appsec-labs.inalyzer5                      5.5b             iNalyzer for iOS 5 client
iHacks-iPad:~ root#

**Comment by essobi** [comment]
Also doesn't appear to be a 5.7.0 binary under releases..

**Comment by sro-co-il** [comment]
I close the issue since it is an old issue. We does no longer support iOS7 and lower. You can fine the new version on our cydia repository https://appsec-labs.com/cydia/
