### ISSUE TITLE
iNalyzer [1/9] Dumping Headers:Failed error dumping headers Failed.

### ISSUE THREAD

**Issue by ghost** [appsec-labs/iNalyzer#5]
Hi,
I tried to contact you via mail, but got no answer.
I get this error every time I try to analyze an application with Hebrew title.
When changing it to English, still no success.

```
XXXs-iPhone:/Applications/iNalyzer5.app root# ./iNalyzer5 YYY
got params /var/mobile/Applications/597FAC17-5E1C-403B-96DA-796991DEA3D0/YYY.app/ YYY.app 282 iNalyzer is iNalyzing YYY...
Application is encryptedDumping ARMV7 portion...helloooo polis?

dyld: F_ADDFILESIGS failed for /tmp/iNalyzer5_abfc881a/Payload/YYY.app/YYY with errno=22
iNalyzer [1/9] Dumping Headers:Failed error dumping headers
Failed.
XXXs-iPhone:/Applications/iNalyzer5.app root# iNalyzer [1/9] Dumping Headers:Failed error dumping headers
-sh: iNalyzer: command not found
XXXs-iPhone:/Applications/iNalyzer5.app root# Failed.
```

Any Help?

**Comment by KiranPanesar** [comment]
I am experiencing the same issue. Any update, @appsec-labs?

**Comment by sro-co-il** [comment]
Did you email inalyzer [at] appsec-labs.com? We try to answer all of the emails.

I close the issue since it is an old issue. If it reproduced on the new version (Available on our cydia repository https://appsec-labs.com/cydia/), please open a new issue.
