### ISSUE TITLE
class-dump-dyld errors

### ISSUE THREAD

**Issue by urbanadventurer** [appsec-labs/iNalyzer#8]
I receive the following error when using the classdump-dyld tool

Test-Users-iPhone:/Applications/iNalyzer5.app root# ./classdump-dyld -o output  -r "/private/var/mobile/Containers/Data/Application/DEADBEEF-DAB1-AAAA-A668-8AAA14975A1B/Library/Application Support/MyMobile_app" -c

   Now dumping /System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64...

  Dumping /System/Library/AccessibilityBundles/AXSpeechImplementation.bundle/AXSpeechImplementation...(3 classes)
  Dumping /System/Library/AccessibilityBundles/AccessibilitySettingsLoader.bundle/AccessibilitySettingsLoader...(15 classes)
2015-09-23 11:17:49.249 classdump-dyld[2283:48107] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* +[NSString stringWithCString:encoding:]: NULL cString'
**\* First throw call stack:
(0x183b602d8 0x1957dc0e4 0x183b60218 0x184998898 0x1000d1d30 0x1000d45e0 0x195e86a08)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by sro-co-il** [comment]
classdump-dyld is an external tool, I can only suggest you to try the other class dump tools.

PS. A new version of iNalyzer was published, available on our cydia repository:
https://appsec-labs.com/cydia/
